import Head from 'next/head'
import { AppProps } from 'next/app'
import { AppStyle } from '@components'
import 'windi.css'

export default ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Death Note</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='https://nextjs.org/static/favicon/favicon.ico' />
        <link rel='stylesheet' href='/_app.css' />
      </Head>
      <AppStyle />
      <Component {...pageProps} />
    </>
  )
}
