import 'windi.css'
import Head from 'next/head'
import { AppProps } from 'next/app'

export default ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://nextjs.org/static/favicon/favicon.ico" />
        <link rel="stylesheet" href="/_app.css" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}
